# Generated by Django 4.0.1 on 2022-10-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_details',
            name='telephone2',
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
    ]
