# Generated by Django 4.0.1 on 2022-10-31 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_chapterlist_coursesummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='body',
            new_name='question',
        ),
    ]
