# Generated by Django 4.0.1 on 2022-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_body_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesummary',
            name='isverified',
            field=models.BooleanField(default=False),
        ),
    ]
